version: 0.2
env:
  variables:
    # Env variables for the application to be deployed
    STAGE: $STAGE
    API_DOMAIN_NAME: $API_DOMAIN_NAME
    LAMBDA_IAM_ROLE_ARN: $LAMBDA_IAM_ROLE_ARN
    LAMBDA_SECURITY_GROUP_IDS: $LAMBDA_SECURITY_GROUP_IDS
    LAMBDA_SUBNET_IDS: $LAMBDA_SUBNET_IDS
    SSM_KEY_NAME_FULL_DB_URL: $SSM_KEY_NAME_FULL_DB_URL
    SSM_KEY_NAME_DJANGO_SECRET_KEY: $SSM_KEY_NAME_DJANGO_SECRET_KEY
    LIMS_BUCKET_NAME: $LIMS_BUCKET_NAME
    LIMS_CSV_OBJECT_KEY: $LIMS_CSV_OBJECT_KEY
    # Env variables for testing
    DEBUG: "on"
    DJANGO_SECRET_KEY: "test-secret"
    DATABASE_URL: mysql://root:test@localhost:3306/data_portal
phases:
  install:
    runtime-versions:
        nodejs: 8
        python: 3.7
    commands:
      # Install dependencies for testing
      - printf 'mysql-server mysql-server/root_password password test' | debconf-set-selection and printf 'mysql-server mysql-server/root_password_again password test' | debconf-set-selections
      - apt-get update && apt-get -y install mysql-server-5.6
      - systemctl start mysql
      - pip3 install -r requirements.txt
      # Install serverless framework
      - npm install
      - npm install -g serverless
  build:
    commands:
      - ./manage.py test
      - SLS_DEBUG=true serverless create_domain --STAGE $STAGE
      - SLS_DEBUG=true serverless deploy --STAGE $STAGE
