version: 0.2
env:
  variables:
    STAGE: $STAGE
    API_DOMAIN_NAME: $API_DOMAIN_NAME
    CERTIFICATE_ARN: $CERTIFICATE_ARN
    WAF_NAME: $WAF_NAME
    LAMBDA_IAM_ROLE_ARN: $LAMBDA_IAM_ROLE_ARN
    LAMBDA_SECURITY_GROUP_IDS: $LAMBDA_SECURITY_GROUP_IDS
    LAMBDA_SUBNET_IDS: $LAMBDA_SUBNET_IDS
    SSM_KEY_NAME_FULL_DB_URL: $SSM_KEY_NAME_FULL_DB_URL
    SSM_KEY_NAME_DJANGO_SECRET_KEY: $SSM_KEY_NAME_DJANGO_SECRET_KEY
    SSM_KEY_NAME_LIMS_SPREADSHEET_ID: $SSM_KEY_NAME_LIMS_SPREADSHEET_ID
    SSM_KEY_NAME_LIMS_SERVICE_ACCOUNT_JSON: $SSM_KEY_NAME_LIMS_SERVICE_ACCOUNT_JSON
    LIMS_BUCKET_NAME: $LIMS_BUCKET_NAME
    LIMS_CSV_OBJECT_KEY: $LIMS_CSV_OBJECT_KEY
phases:
  install:
    runtime-versions:
        nodejs: 12
        python: 3.8
    commands:
      - pip install '.[test]' -r requirements.txt
      - yarn global add serverless
      - yarn install
  build:
    commands:
      - ./manage.py test
      - SLS_DEBUG=true serverless create_domain --STAGE $STAGE
      - SLS_DEBUG=true serverless deploy --STAGE $STAGE
