version: 0.2
env:
  variables:
    STAGE: $STAGE
    IAP_BASE_URL: $IAP_BASE_URL
    IAP_AUTH_TOKEN: $IAP_AUTH_TOKEN
    DJANGO_SETTINGS_MODULE: data_portal.settings.it
phases:
  install:
    runtime-versions:
        nodejs: 12
        python: 3.8
    commands:
      - pip install -r requirements-test.txt
      - yarn install
  build:
    commands:
      - which docker
      - which docker-compose
      - which python3
      - docker-compose up -d
      - make load_localstack
      - python3 manage.py test
      - docker-compose down
      - SLS_DEBUG=true npx serverless create_domain --STAGE $STAGE
      - SLS_DEBUG=true npx serverless deploy --STAGE $STAGE
