version: 0.2
env:
  variables:
    STAGE: $STAGE
    IAP_BASE_URL: $IAP_BASE_URL
    IAP_AUTH_TOKEN: $IAP_AUTH_TOKEN
    DJANGO_SETTINGS_MODULE: data_portal.settings.aws
phases:
  install:
    runtime-versions:
        nodejs: 12
        python: 3.8
    commands:
      - pip install -r requirements-test.txt
      - yarn global add serverless
      - yarn install
  build:
    commands:
      - which docker
      - which docker-compose
      - which python3
      - which serverless
      - docker-compose -f it-mock.yml -p it_mock up -d
      - make load_localstack
      - python3 manage.py test
      - docker-compose -f it-mock.yml -p it_mock down
      - SLS_DEBUG=true serverless create_domain --STAGE $STAGE
      - SLS_DEBUG=true serverless deploy --STAGE $STAGE
