version: 0.2
env:
  variables:
    STAGE: $STAGE
    API_DOMAIN_NAME: $API_DOMAIN_NAME
    CERTIFICATE_ARN: $CERTIFICATE_ARN
    WAF_NAME: $WAF_NAME
    LAMBDA_IAM_ROLE_ARN: $LAMBDA_IAM_ROLE_ARN
    LAMBDA_SECURITY_GROUP_IDS: $LAMBDA_SECURITY_GROUP_IDS
    LAMBDA_SUBNET_IDS: $LAMBDA_SUBNET_IDS
    SSM_KEY_NAME_FULL_DB_URL: $SSM_KEY_NAME_FULL_DB_URL
    SSM_KEY_NAME_DJANGO_SECRET_KEY: $SSM_KEY_NAME_DJANGO_SECRET_KEY
    SSM_KEY_NAME_METADATA_TRACKING_SHEET_ID: $SSM_KEY_NAME_METADATA_TRACKING_SHEET_ID
    SSM_KEY_NAME_LIMS_SPREADSHEET_ID: $SSM_KEY_NAME_LIMS_SPREADSHEET_ID
    SSM_KEY_NAME_LIMS_SERVICE_ACCOUNT_JSON: $SSM_KEY_NAME_LIMS_SERVICE_ACCOUNT_JSON
    SSM_KEY_NAME_IAP_AUTH_TOKEN: $SSM_KEY_NAME_IAP_AUTH_TOKEN
    SERVERLESS_DEPLOYMENT_BUCKET: $SERVERLESS_DEPLOYMENT_BUCKET
    SLACK_CHANNEL: $SLACK_CHANNEL
    DJANGO_SETTINGS_MODULE: data_portal.settings.aws
    IAP_BASE_URL: $IAP_BASE_URL
    IAP_AUTH_TOKEN: $IAP_AUTH_TOKEN
phases:
  install:
    runtime-versions:
        nodejs: 12
        python: 3.8
    commands:
      - pip install -r requirements-test.txt
      - yarn global add serverless
      - yarn install
  build:
    commands:
      - which docker
      - which docker-compose
      - which python3
      - which serverless
      - docker-compose -f iap-mock.yml -p iap_mock up -d
      - python3 manage.py test
      - docker-compose -f iap-mock.yml -p iap_mock down
      - SLS_DEBUG=true serverless create_domain --STAGE $STAGE
      - SLS_DEBUG=true serverless deploy --STAGE $STAGE
