version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 8
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage ${STAGE}
