version: 0.2
env:
  variables:
    STAGE: $STAGE
    API_DOMAIN_NAME: $API_DOMAIN_NAME
    LAMBDA_IAM_ROLE_ARN: $LAMBDA_IAM_ROLE_ARN
    LAMBDA_SECURITY_GROUP_IDS: $LAMBDA_SECURITY_GROUP_IDS
    LAMBDA_SUBNET_IDS: $LAMBDA_SUBNET_IDS
    SSM_KEY_NAME_FULL_DB_URL: $SSM_KEY_NAME_FULL_DB_URL
    SSM_KEY_NAME_DJANGO_SECRET_KEY: $SSM_KEY_NAME_DJANGO_SECRET_KEY
    LIMS_BUCKET_NAME: $LIMS_BUCKET_NAME
    LIMS_CSV_OBJECT_KEY: $LIMS_CSV_OBJECT_KEY
phases:
  install:
    runtime-versions:
        nodejs: 8
        python: 3.7
    commands:
      - npm install
      - npm install -g serverless
  build:
    commands:
      - SLS_DEBUG=true serverless create_domain --STAGE $STAGE
      - serverless deploy --STAGE $STAGE
