version: 0.2
env:
  variables:
    STAGE: $STAGE
    ICA_BASE_URL: $ICA_BASE_URL
    ICA_ACCESS_TOKEN: $ICA_ACCESS_TOKEN
    DJANGO_SETTINGS_MODULE: data_portal.settings.it
phases:
  install:
    runtime-versions:
        nodejs: 14
        python: 3.9
    commands:
      - pip install -r requirements-test.txt
      - yarn install
  build:
    commands:
      - which docker
      - which docker-compose
      - which python3
      - which aws
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      - make load_localstack
      - python3 manage.py test
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down
      - SLS_DEBUG=true npx serverless create_domain --stage $STAGE
      - SLS_DEBUG=true npx serverless deploy --stage $STAGE
      - SLS_DEBUG=true npx serverless invoke -f migrate --stage $STAGE
