version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 8
    commands:
      - npm install
      # Use fixed version for now. See https://github.com/serverless/serverless/issues/6414
      - npm install -g serverless@1.48.0
  build:
    commands:
      - SLS_DEBUG=true serverless create_domain --STAGE $STAGE
                                                --API_DOMAIN_NAME $API_DOMAIN_NAME
                                                --ATHENA_OUTPUT_LOCATION $ATHENA_OUTPUT_LOCATION
                                                --S3_KEYS_TABLE_NAME $S3_KEYS_TABLE_NAME
                                                --LIMS_TABLE_NAME $LIMS_TABLE_NAME
                                                --LAMBDA_IAM_ROLE_ARN $LAMBDA_IAM_ROLE_ARN
      - serverless deploy --STAGE $STAGE
                          --API_DOMAIN_NAME $API_DOMAIN_NAME
                          --ATHENA_OUTPUT_LOCATION $ATHENA_OUTPUT_LOCATION
                          --S3_KEYS_TABLE_NAME $S3_KEYS_TABLE_NAME
                          --LIMS_TABLE_NAME $LIMS_TABLE_NAME
                          --LAMBDA_IAM_ROLE_ARN $LAMBDA_IAM_ROLE_ARN
