version: 0.2
env:
  shell: bash
  variables:
    STAGE: $STAGE
    ICA_BASE_URL: $ICA_BASE_URL
    ICA_ACCESS_TOKEN: $ICA_ACCESS_TOKEN
    DJANGO_SETTINGS_MODULE: data_portal.settings.it
phases:
  install:
    runtime-versions:
        nodejs: 18
        python: 3.11
    commands:
      - ps -p $$
      - python -m venv .venv
      - source .venv/bin/activate
      - which python
      - which pip
      - pip install -U pip
      - pip install -r requirements-test.txt
      - npx yarn install
  build:
    commands:
      - which docker
      - which docker-compose
      - which aws
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      - make load_localstack
      - python manage.py test
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down
      - npx serverless create_domain
      - npx serverless deploy --stage $STAGE
      - npx serverless invoke -f migrate --stage $STAGE
