version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data_portal
      - MYSQL_USER=data_portal
      - MYSQL_PASSWORD=data_portal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4572:4572"
      - "4576:4576"
      - "${PORT_WEB_UI-8282}:${PORT_WEB_UI-8080}"
    environment:
      - DEFAULT_REGION=${AWS_DEFAULT_REGION-ap-southeast-2}
      - SERVICES=sqs,s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
