version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data_portal
      - MYSQL_USER=data_portal
      - MYSQL_PASSWORD=data_portal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
