# NOTE:
# This is for CodeBuild CI/CD override. Need to specify explicitly like so:
# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
#
# Made a copy there in quay due to dockerhub rate limit.

version: '3.1'

services:

  db:
    image: public.ecr.aws/docker/library/mysql:8.4

  localstack:
    image: public.ecr.aws/localstack/localstack:3

  haproxy:
    image: public.ecr.aws/docker/library/haproxy:2.8

  wes:
    image: quay.io/victorskl/prism:5

  tes:
    image: quay.io/victorskl/prism:5

  gds:
    image: quay.io/victorskl/prism:5

  ens:
    image: quay.io/victorskl/prism:5

  console:
    image: quay.io/victorskl/prism:5

  v2:
    image: quay.io/victorskl/prism:5
