version: '3.1'

services:

  haproxy:
    image: haproxy
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  wes:
    image: stoplight/prism:3
    command: mock -d -h 0.0.0.0 "/swagger/wes.json"
    restart: always
    ports:
      - 4010:4010
    volumes:
      - ./swagger:/swagger

  tes:
    image: stoplight/prism:3
    command: mock -d -h 0.0.0.0 "/swagger/tes.json"
    restart: always
    ports:
      - 4011:4010
    volumes:
      - ./swagger:/swagger

  gds:
    image: stoplight/prism:3
    command: mock -d -h 0.0.0.0 "/swagger/gds.json"
    restart: always
    ports:
      - 4012:4010
    volumes:
      - ./swagger:/swagger

  ens:
    image: stoplight/prism:3
    command: mock -d -h 0.0.0.0 "/swagger/ens.json"
    restart: always
    ports:
      - 4013:4010
    volumes:
      - ./swagger:/swagger

  console:
    image: stoplight/prism:3
    command: mock -d -h 0.0.0.0 "/swagger/console.json"
    restart: always
    ports:
      - 4014:4010
    volumes:
      - ./swagger:/swagger
