service: data-portal-app-api

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  # - serverless-domain-manager
  - serverless-aws-documentation
  - serverless-associate-waf

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:STAGE}
  region: ap-southeast-2
  role: ${env:LAMBDA_IAM_ROLE_ARN}
  vpc:
    securityGroupIds:
      "Fn::Split":
        - ","
        - ${env:RDS_SECURITY_GROUP_IDS}
    subnetIds:
      "Fn::Split":
        - ","
        - ${env:RDS_SUBNET_IDS}
  environment:
    SSM_KEY_NAME_DJANGO_SECRET_KEY: ${env:SSM_KEY_NAME_DJANGO_SECRET_KEY}
    SSM_KEY_NAME_FULL_DB_URL: ${env:SSM_KEY_NAME_FULL_DB_URL}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
        authorizer: aws_iam
      - http:  ANY {proxy+}
        authorizer: aws_iam
  s3_data_processor:
    handler: process_sqs_records.handler
    events:
      - sqs:
        arn: arn:aws:sqs:ap-southeast-2:620123204273:data-portal-test

custom:
  wsgi:
    app: django.wsgi.application
#  customDomain:
#    domainName: ${env:API_DOMAIN_NAME}
#    basePath: ''
#    stage: ${self:provider.stage}
#    createRoute53Record: true
#  associateWaf:
#    name: dataPortalAPIWebAcl
