# NOTE: update this with your service name
service: data-portal-app-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  customDomain:
    domainName: api.${opt:DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:STAGE}
  region: ap-southeast-2
  timeout: 20

  iamRoleStatements:
    - Effect: Allow
      Action: [
        "athena:BatchGetQueryExecution",
        "athena:CancelQueryExecution",
        "athena:GetCatalogs",
        "athena:GetExecutionEngine",
        "athena:GetExecutionEngines",
        "athena:GetNamespace",
        "athena:GetNamespaces",
        "athena:GetQueryExecution",
        "athena:GetQueryExecutions",
        "athena:GetQueryResults",
        "athena:GetQueryResultsStream",
        "athena:GetTable",
        "athena:GetTables",
        "athena:ListQueryExecutions",
        "athena:RunQuery",
        "athena:StartQueryExecution",
        "athena:StopQueryExecution",
        "s3:GetBucketLocation",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:ListBucketMultipartUploads",
        "s3:ListMultipartUploadParts",
        "s3:AbortMultipartUpload",
        "s3:PutObject",
        "glue:*"
      ]
      Resource: "*"

functions:
  file-search:
    handler: file-search.main
    events:
      - http:
          path: files
          method: get
          cors: true
          authorizer: aws_iam
    environment:
      ATHENA_OUTPUT_LOCATION: ${opt:ATHENA_OUTPUT_LOCATION}
      S3_KEYS_TABLE_NAME: ${opt:S3_KEYS_TABLE_NAME}
      LIMS_TABLE_NAME: ${opt:LIMS_TABLE_NAME}

  file-signed-url:
    handler: file-signed-url.main
    events:
      - http:
          path: file-signed-url
          method: get
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/api-gateway-errors.yml)}