service: data-portal-api

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-aws-documentation
  - serverless-associate-waf
  - serverless-plugin-scripts

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:STAGE}
  region: ap-southeast-2
  deploymentBucket: ${ssm:/data_portal/backend/serverless_deployment_bucket}
  role: ${ssm:/data_portal/backend/lambda_iam_role_arn}
  vpc:
    securityGroupIds:
      "Fn::Split":
        - ","
        - ${ssm:/data_portal/backend/lambda_security_group_ids}
    subnetIds:
      "Fn::Split":
        - ","
        - ${ssm:/data_portal/backend/lambda_subnet_ids}
  environment:
    DJANGO_SETTINGS_MODULE: data_portal.settings.aws

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          integration: lambda-proxy
          authorizer: aws_iam
          cors: true
  migrate:
    handler: migrate.handler
    timeout: 20
  lims_scheduled_update_processor:
    handler: data_processors.lims.lambdas.scheduled_update_handler
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          enabled: ${self:custom.enabled.${opt:STAGE}, self.enabled.other}
    timeout: 28
  sqs_s3_event_processor:
    handler: data_processors.s3.lambdas.handler
    events:
      - sqs:
          arn: ${ssm:/data_portal/backend/s3_event_sqs_arn}
    timeout: 28
  sqs_iap_event_processor:
    handler: data_processors.pipeline.lambdas.sqs_iap_event.handler
    events:
      - sqs:
          arn: ${ssm:/data_portal/backend/iap_ens_event_sqs_arn}
    timeout: 28
  sqs_germline_event_processor:
    handler: data_processors.pipeline.lambdas.germline.sqs_handler
    events:
      - sqs:
          arn: ${ssm:/data_portal/backend/sqs_germline_queue_arn}
    timeout: 28
  sqs_notification_event_processor:
    handler: data_processors.pipeline.lambdas.notification.sqs_handler
    events:
      - sqs:
          arn: ${ssm:/data_portal/backend/sqs_notification_queue_arn}
    timeout: 28
  bcl_convert:
    handler: data_processors.pipeline.lambdas.bcl_convert.handler
    timeout: 28
  germline:
    handler: data_processors.pipeline.lambdas.germline.handler
    timeout: 28
  fastq:
    handler: data_processors.pipeline.lambdas.fastq.handler
    timeout: 28
  orchestrator:
    handler: data_processors.pipeline.lambdas.orchestrator.handler
    timeout: 28
  workflow_update:
    handler: data_processors.pipeline.lambdas.workflow_update.handler
    timeout: 28
  wes_launch:
    handler: data_processors.pipeline.lambdas.wes_handler.launch
    timeout: 28
  wes_get_workflow_run:
    handler: data_processors.pipeline.lambdas.wes_handler.get_workflow_run
    timeout: 28
  demux_metadata:
    handler: data_processors.pipeline.lambdas.demux_metadata.handler
    timeout: 28
  notification:
    handler: data_processors.pipeline.lambdas.notification.handler
    timeout: 28

custom:
  enabled:
    dev: false
    prod: true
    other: false
  wsgi:
    app: data_portal.wsgi.application
    packRequirements: false
  scripts:
    hooks:
      'deploy:finalize': SLS_DEBUG=true sls invoke -f migrate --STAGE ${opt:STAGE} --noinput
  pythonRequirements:
     zip: true
     slim: true
     slimPatternsAppendDefaults: false
     slimPatterns:
       - '**/*.py[c|o]'
       - '**/__pycache__*'
  customDomain:
    domainName: ${ssm:/data_portal/backend/api_domain_name}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateArn: ${ssm:/data_portal/backend/certificate_arn}
  associateWaf:
    name: ${ssm:/data_portal/backend/waf_name}
package:
  exclude:
    - node_modules/**
    - mocks/**
    - downloads/**
    - venv/**
    - .venv/**
    - env/**
    - data/**
    - docker-compose.yml
    - docker-compose.override.sample.yml
    - docker-compose.override.yml
    - haproxy.cfg
    - start.sh
    - loaddata.sh
