# generated by datamodel-codegen:
#   filename:  WorkflowRunStateChange.schema.json
#   timestamp: 2023-09-12T07:58:42+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, AliasChoices


class WorkflowRunStateChange(BaseModel):
    portal_run_id: str
    type_name: str
    version: str
    output: str
    end_status: str
    wfr_name: Optional[str] = None
    wfr_id: Optional[str] = None
    wfv_id: Optional[str] = None
    wfl_id: Optional[str] = None
    end: Optional[datetime] = None


class WorkflowRunStateChangeEnvelope(BaseModel):
    id: str
    detail_type: str = Field(
        default='Workflow Run State Change',
        serialization_alias='detail-type',
        validation_alias=AliasChoices('detail-type', 'detail_type')
    )
    source: str
    time: str
    detail: WorkflowRunStateChange
