# Generated by Django 2.1.4 on 2019-08-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LIMSRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illumina_id', models.CharField(max_length=255)),
                ('run', models.IntegerField()),
                ('timestamp', models.DateField()),
                ('sample_id', models.CharField(max_length=255)),
                ('sample_name', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('subject_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('phenotype', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('secondary_analysis', models.CharField(max_length=255)),
                ('fastq', models.CharField(max_length=255)),
                ('number_fastqs', models.CharField(max_length=255)),
                ('results', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='S3LIMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lims_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_portal.LIMSRow')),
            ],
        ),
        migrations.CreateModel(
            name='S3Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('last_modified_date', models.DateTimeField()),
                ('e_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='s3object',
            unique_together={('bucket', 'key')},
        ),
        migrations.AddField(
            model_name='s3lims',
            name='s3_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_portal.S3Object'),
        ),
        migrations.AlterUniqueTogether(
            name='s3lims',
            unique_together={('s3_object', 'lims_row')},
        ),
    ]
