# Generated by Django 4.0.2 on 2022-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0001_squashed_0037_workflow_portal_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('failed', 'Failed'), ('succeeded', 'Succeeded'), ('aborted', 'Aborted')], max_length=255),
        ),
    ]
