# Generated by Django 2.1.4 on 2019-08-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsrow',
            name='todo',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='trello',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
