# Generated by Django 3.2.7 on 2021-10-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0001_squashed_0037_auto_20211028_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limsrow',
            name='library_id',
            field=models.CharField(max_length=255),
        ),
    ]
