# Generated by Django 4.0.7 on 2022-10-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0002_alter_sequence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmetadata',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
