# Generated by Django 4.0.7 on 2022-10-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0003_alter_labmetadata_sample_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
