# Generated by Django 2.1.4 on 2019-08-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0003_limsrow_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limsrow',
            name='notes',
            field=models.TextField(),
        ),
    ]
