# Generated by Django 2.1.11 on 2019-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0004_auto_20190829_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limsrow',
            name='project',
        ),
        migrations.AddField(
            model_name='limsrow',
            name='assay',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='external_library_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='external_sample_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='external_subject_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='library_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='project_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='project_owner',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limsrow',
            name='topup',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
