# Generated by Django 4.1.7 on 2023-02-27 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0004_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('phenotype', models.CharField(max_length=255)),
                ('cov_median_mosdepth', models.IntegerField()),
                ('cov_auto_median_dragen', models.FloatField()),
                ('reads_tot_input_dragen', models.BigIntegerField()),
                ('reads_mapped_pct_dragen', models.FloatField()),
                ('insert_len_median_dragen', models.IntegerField()),
                ('var_tot_dragen', models.BigIntegerField()),
                ('var_snp_dragen', models.FloatField()),
                ('ploidy', models.FloatField()),
                ('purity', models.FloatField()),
                ('qc_status_purple', models.BooleanField()),
                ('sex', models.BooleanField()),
                ('ms_status', models.CharField(max_length=255)),
                ('tmb', models.FloatField()),
                ('s3_object_id', models.BigIntegerField(blank=True, null=True)),
                ('gds_file_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
