# Generated by Django 4.1.7 on 2023-03-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0005_flowmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmetrics',
            name='qc_status_purple',
            field=models.CharField(max_length=255),
        ),
    ]
