# Generated by Django 2.1.11 on 2019-10-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0006_auto_20191001_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limsrow',
            name='assay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='external_library_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='external_sample_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='external_subject_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='fastq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='number_fastqs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='phenotype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='project_owner',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='quality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='results',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='sample_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='secondary_analysis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='subject_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='todo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='topup',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='trello',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
