# Generated by Django 4.1.7 on 2023-03-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0006_alter_flowmetrics_qc_status_purple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmetrics',
            name='gds_file_id',
            field=models.CharField(default='afc598783c8f188dbd8d7faba9b7f011498fd618a09a4d9ecc8521f95730c7da', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowmetrics',
            name='phenotype',
            field=models.CharField(choices=[('normal', 'Normal'), ('tumor', 'Tumor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='flowmetrics',
            name='qc_status_purple',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Na')], max_length=255),
        ),
        migrations.AlterField(
            model_name='flowmetrics',
            name='s3_object_id',
            field=models.CharField(default='afc598783c8f188dbd8d7faba9b7f011498fd618a09a4d9ecc8521f95730c7da', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowmetrics',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('na', 'Na')], max_length=255),
        ),
    ]
