# Generated by Django 4.2.3 on 2023-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0006_alter_workflow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='portal_run_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
