# Generated by Django 4.2.3 on 2023-09-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0007_alter_workflow_portal_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='sample_name',
        ),
    ]
