# Generated by Django 4.1.7 on 2023-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0007_alter_flowmetrics_gds_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowmetrics',
            name='sample_id',
        ),
        migrations.RemoveField(
            model_name='flowmetrics',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='flowmetrics',
            name='portal_run_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flowmetrics',
            name='gds_file_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flowmetrics',
            name='s3_object_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
