# Generated by Django 2.1.11 on 2019-10-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0007_auto_20191002_0603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='limsrow',
            unique_together={('illumina_id', 'library_id')},
        ),
    ]
