# Generated by Django 4.2.3 on 2023-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0008_remove_workflow_sample_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='wfl_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='wfr_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='wfv_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
