# Generated by Django 4.1.7 on 2023-03-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0008_remove_flowmetrics_sample_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmetrics',
            name='phenotype',
            field=models.CharField(choices=[('negative-control', 'N Control'), ('normal', 'Normal'), ('tumor', 'Tumor')], max_length=255),
        ),
    ]
