# Generated by Django 3.0.2 on 2020-01-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0009_auto_20191016_0050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='s3object',
            unique_together=set(),
        ),
    ]
