# Generated by Django 4.1.7 on 2023-03-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0009_alter_flowmetrics_phenotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmetrics',
            name='ploidy',
            field=models.FloatField(null=True),
        ),
    ]
