# Generated by Django 5.1.1 on 2024-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_portal",
            "0010_alter_labmetadata_assay_alter_labmetadata_quality_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="s3object",
            index=models.Index(fields=["bucket"], name="data_portal_bucket_3e12a9_idx"),
        ),
    ]
