# Generated by Django 4.1.7 on 2023-03-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0010_alter_flowmetrics_ploidy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmetrics',
            name='tmb',
            field=models.FloatField(null=True),
        ),
    ]
