# Generated by Django 3.0.2 on 2020-01-23 06:49

import data_portal.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0010_auto_20200123_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3object',
            name='unique_hash',
            field=data_portal.fields.HashField(base_fields=['bucket', 'key'], null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='fastq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limsrow',
            name='trello',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3object',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='s3object',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
