# Generated by Django 4.1.7 on 2023-03-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0011_alter_flowmetrics_tmb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowmetrics',
            old_name='gds_file_id',
            new_name='athena_job_id',
        ),
        migrations.RemoveField(
            model_name='flowmetrics',
            name='s3_object_id',
        ),
    ]
