# Generated by Django 3.0.2 on 2020-01-23 06:55

from django.db import migrations


def process_unique_hash(apps, schema_editor):
    S3Object = apps.get_model('data_portal', 'S3Object')
    for s3 in S3Object.objects.all():
        s3.save()


class Migration(migrations.Migration):
    dependencies = [
        ('data_portal', '0011_auto_20200123_0649'),
    ]

    operations = [
        migrations.RunPython(process_unique_hash, elidable=True),
    ]
