# Generated by Django 5.1.2 on 2024-11-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_portal", "0011_s3object_data_portal_bucket_3e12a9_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=255)),
                (
                    "gen",
                    models.IntegerField(
                        choices=[
                            (0, "unknown"),
                            (1, "bcbio"),
                            (2, "icav1"),
                            (3, "icav2"),
                        ]
                    ),
                ),
                (
                    "method",
                    models.IntegerField(
                        choices=[
                            (0, "unclassified"),
                            (1, "wgts"),
                            (2, "sash"),
                            (3, "cttso"),
                            (4, "cttsov2"),
                        ]
                    ),
                ),
                ("gdsfiles", models.ManyToManyField(to="data_portal.gdsfile")),
                ("s3objects", models.ManyToManyField(to="data_portal.s3object")),
            ],
            options={
                "unique_together": {("key", "gen", "method")},
            },
        ),
    ]
