# Generated by Django 3.0.2 on 2020-01-23 07:05

import data_portal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0012_auto_20200123_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3object',
            name='unique_hash',
            field=data_portal.fields.HashField(base_fields=['bucket', 'key'], default=None, unique=True),
        ),
    ]
