# Generated by Django 3.0.4 on 2020-04-03 00:34

import data_portal.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0013_auto_20200123_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('volume_id', models.CharField(max_length=255)),
                ('volume_name', models.TextField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_id', models.CharField(max_length=255)),
                ('sub_tenant_id', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('time_created', models.DateTimeField()),
                ('created_by', models.CharField(max_length=255)),
                ('time_modified', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=255)),
                ('inherited_acl', models.TextField()),
                ('urn', models.TextField()),
                ('size_in_bytes', models.BigIntegerField()),
                ('is_uploaded', models.BooleanField(null=True)),
                ('archive_status', models.CharField(max_length=255)),
                ('time_archived', models.DateTimeField(blank=True, null=True)),
                ('storage_tier', models.CharField(max_length=255)),
                ('presigned_url', models.TextField(blank=True, null=True)),
                ('unique_hash', data_portal.fields.HashField(base_fields=['volume_name', 'path'], default=None, unique=True)),
            ],
        ),
    ]
