# Generated by Django 3.0.4 on 2020-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0014_gdsfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdsfile',
            name='inherited_acl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
