# Generated by Django 3.0.4 on 2020-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0015_auto_20200416_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('gds_folder_path', models.TextField()),
                ('gds_volume_name', models.TextField()),
                ('reagent_barcode', models.CharField(max_length=255)),
                ('v1pre3_id', models.CharField(max_length=255)),
                ('acl', models.TextField()),
                ('flowcell_barcode', models.CharField(max_length=255)),
                ('sample_sheet_name', models.CharField(max_length=255)),
                ('api_url', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('instrument_run_id', models.CharField(max_length=255)),
                ('msg_attr_action', models.CharField(max_length=255)),
                ('msg_attr_action_type', models.CharField(max_length=255)),
                ('msg_attr_action_date', models.DateTimeField()),
                ('msg_attr_produced_by', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('run_id', 'date_modified', 'status')},
            },
        ),
    ]
