# Generated by Django 3.0.7 on 2020-06-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0016_sequencerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfr_id', models.CharField(max_length=255)),
                ('wfl_id', models.CharField(max_length=255)),
                ('wfv_id', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('input', models.TextField()),
                ('start', models.DateTimeField()),
                ('output', models.TextField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('end_status', models.CharField(blank=True, max_length=255, null=True)),
                ('fastq_read_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parents', models.TextField(blank=True, null=True)),
                ('sequence_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_portal.SequenceRun')),
            ],
            options={
                'unique_together': {('wfr_id', 'wfl_id', 'wfv_id')},
            },
        ),
    ]
