# Generated by Django 3.0.7 on 2020-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0017_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='wfr_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
