# Generated by Django 3.0.7 on 2020-06-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0018_workflow_wfr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
