# Generated by Django 3.1.1 on 2020-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0018_auto_20201007_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='notified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
