# Generated by Django 3.1.1 on 2020-12-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_batchrun_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(auto_created=True)),
                ('hrd_hrdetect', models.TextField(blank=True, null=True)),
                ('hrd_results_hrdetect', models.IntegerField(blank=True, null=True)),
                ('hrd_chord', models.TextField(blank=True, null=True)),
                ('hrd_chord2', models.IntegerField(blank=True, null=True)),
                ('hrd_results_chord', models.TextField(blank=True, null=True)),
                ('hrd_results_chord2', models.IntegerField(blank=True, null=True)),
                ('purple_sample_type', models.CharField(max_length=4)),
                ('purple_chr', models.CharField(max_length=10)),
                ('purple_start', models.BigIntegerField()),
                ('purple_end', models.BigIntegerField()),
                ('purple_CN', models.IntegerField()),
                ('purple_ploidy_min_maj', models.CharField(max_length=3)),
                ('purple_start_end_segsupport', models.TextField(blank=True, null=True)),
                ('purple_method', models.TextField(blank=True, null=True)),
                ('purple_BAF_count', models.TextField(blank=True, null=True)),
                ('purple_GC_window_count', models.TextField(blank=True, null=True)),
                ('purple_gene', models.TextField(blank=True, null=True)),
                ('purple_minCN', models.TextField(blank=True, null=True)),
                ('purple_maxCN', models.TextField(blank=True, null=True)),
                ('purple_chr_band', models.TextField(blank=True, null=True)),
                ('purple_onco_or_ts', models.TextField(blank=True, null=True)),
                ('purple_transcript_id', models.TextField(blank=True, null=True)),
                ('purple_min_minor_allele_ploidy', models.TextField(blank=True, null=True)),
                ('purple_som_reg', models.TextField(blank=True, null=True)),
                ('purple_gem_del_reg', models.TextField(blank=True, null=True)),
                ('purple_min_reg', models.TextField(blank=True, null=True)),
                ('purple_min_reg_start_end', models.TextField(blank=True, null=True)),
                ('purple_min_reg_supported_start_end_method', models.TextField(blank=True, null=True)),
                ('sigs_rank', models.IntegerField()),
                ('sigs_signature', models.CharField(max_length=5)),
                ('sigs_contribution', models.IntegerField()),
                ('sigs_freq', models.IntegerField()),
                ('sv_vcfnum', models.IntegerField()),
                ('sv_tiertop', models.IntegerField()),
                ('sv_start', models.TextField()),
                ('sv_end', models.TextField()),
                ('sv_type', models.TextField()),
                ('sv_id', models.TextField()),
                ('sv_pr_alt', models.IntegerField()),
                ('sv_sr_pr_ref', models.TextField()),
                ('sv_ploidy', models.TextField()),
                ('sv_af_purple', models.TextField()),
                ('sv_af_bpi', models.TextField()),
                ('sv_cnc', models.TextField()),
                ('sv_cn', models.TextField()),
                ('sv_sscore', models.IntegerField()),
                ('sv_nann', models.IntegerField()),
                ('sv_annotation', models.TextField()),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_portal.limsrow')),
            ],
        ),
    ]
