# Generated by Django 3.1.1 on 2021-02-26 03:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_batchrun_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('library_id', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('subject_id', 'sample_id', 'library_id')},
            },
        ),
        migrations.CreateModel(
            name='HRDReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data_portal.report')),
                ('hrd_report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hrd_probability', models.FloatField(blank=True, null=True)),
                ('hrd_intercept', models.FloatField(blank=True, null=True)),
                ('hrd_del_mh_prop', models.FloatField(blank=True, null=True)),
                ('hrd_SNV3', models.FloatField(blank=True, null=True)),
                ('hrd_SV3', models.FloatField(blank=True, null=True)),
                ('hrd_SV5', models.FloatField(blank=True, null=True)),
                ('hrd_hrdloh_index', models.FloatField(blank=True, null=True)),
                ('hrd_SNV8', models.FloatField(blank=True, null=True)),
            ],
            bases=('data_portal.report',),
        ),
    ]
