# Generated by Django 3.1.1 on 2021-04-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_batchrun_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastqListRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgid', models.CharField(max_length=255)),
                ('rgsm', models.CharField(max_length=255)),
                ('rglb', models.CharField(max_length=255)),
                ('lane', models.IntegerField()),
                ('read_1', models.TextField()),
                ('read_2', models.TextField(blank=True, null=True)),
                ('sequence_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_portal.sequencerun')),
            ],
            options={
                'unique_together': {('rgid',)},
            },
        ),
    ]
