# Generated by Django 3.0.7 on 2020-06-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_workflow_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='notified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
