# Generated by Django 3.1.1 on 2021-03-12 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_batchrun_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('library_id', models.CharField(max_length=255)),
                ('purple_sample_type', models.CharField(max_length=255)),
                ('purple_chr', models.CharField(max_length=255)),
                ('purple_start', models.BigIntegerField(blank=True, null=True)),
                ('purple_end', models.BigIntegerField(blank=True, null=True)),
                ('purple_CN', models.IntegerField(blank=True, null=True)),
                ('purple_ploidy_min_maj', models.CharField(max_length=255)),
                ('purple_start_end_segsupport', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_method', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_BAF_count', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_GC_window_count', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_gene', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_minCN', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_maxCN', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_chr_band', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_onco_or_ts', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_transcript_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_minor_allele_ploidy', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_som_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_gem_del_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_reg_start_end', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_reg_supported_start_end_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('subject_id', 'sample_id', 'library_id')},
            },
        ),
        migrations.CreateModel(
            name='HRDReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('library_id', models.CharField(max_length=255)),
                ('hrd_probability', models.FloatField(blank=True, null=True)),
                ('hrd_intercept', models.FloatField(blank=True, null=True)),
                ('hrd_del_mh_prop', models.FloatField(blank=True, null=True)),
                ('hrd_SNV3', models.FloatField(blank=True, null=True)),
                ('hrd_SV3', models.FloatField(blank=True, null=True)),
                ('hrd_SV5', models.FloatField(blank=True, null=True)),
                ('hrd_hrdloh_index', models.FloatField(blank=True, null=True)),
                ('hrd_SNV8', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('subject_id', 'sample_id', 'library_id')},
            },
        ),
    ]
