# Generated by Django 3.1.1 on 2021-03-16 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_batchrun_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('library_id', models.CharField(max_length=255)),
                ('purple', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('subject_id', 'sample_id', 'library_id')},
            },
        ),
        migrations.CreateModel(
            name='HRDReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('library_id', models.CharField(max_length=255)),
                ('hrd', models.JSONField(blank=True, null=True)),
            ],
            bases=('data_portal.report',),
        ),
    ]
