# Generated by Django 3.1.1 on 2021-03-17 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0019_batchrun_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('library_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('subject_id', 'sample_id', 'library_id', 'type', 'date_created')},
            },
        ),
    ]
