# Generated by Django 3.1.1 on 2021-03-12 03:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0020_cancer_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data_portal.report')),
                ('purple_report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purple_sample_type', models.CharField(max_length=255)),
                ('purple_chr', models.CharField(max_length=255)),
                ('purple_start', models.BigIntegerField(blank=True, null=True)),
                ('purple_end', models.BigIntegerField(blank=True, null=True)),
                ('purple_CN', models.IntegerField(blank=True, null=True)),
                ('purple_ploidy_min_maj', models.CharField(max_length=255)),
                ('purple_start_end_segsupport', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_method', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_BAF_count', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_GC_window_count', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_gene', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_minCN', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_maxCN', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_chr_band', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_onco_or_ts', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_transcript_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_minor_allele_ploidy', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_som_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_gem_del_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_reg', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_reg_start_end', models.CharField(blank=True, max_length=255, null=True)),
                ('purple_min_reg_supported_start_end_method', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('data_portal.report',),
        ),
    ]
