# Generated by Django 3.1.1 on 2020-12-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0021_auto_20201204_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sample_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_portal.limsrow'),
        ),
    ]
