# Generated by Django 3.1.8 on 2021-04-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0020_fastqlistrow'),
        ('data_portal', '0021_auto_20210319_0057'),
    ]

    operations = [
    ]
