# Generated by Django 3.1.8 on 2021-04-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0022_merge_20210411_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='s3_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_portal.s3object'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('subject_id', 'sample_id', 'library_id', 'type')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_created',
        ),
    ]
