# Generated by Django 3.1.1 on 2021-02-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0023_auto_20210218_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='hrd_chord',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_chord2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_hrdetect',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_results_chord',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_results_chord2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_results_hrdetect',
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_SNV3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_SNV8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_SV3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_SV5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_del_mh_prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_hrdloh_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_intercept',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='hrd_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
