# Generated by Django 3.1.1 on 2021-02-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0024_auto_20210225_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='library_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='sample_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
