# Generated by Django 3.2 on 2021-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0025_auto_20210427_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='s3_object',
        ),
        migrations.AddField(
            model_name='report',
            name='s3_object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
