# Generated by Django 3.1.1 on 2021-02-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0025_auto_20210225_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrd_probability', models.FloatField(blank=True, null=True)),
                ('hrd_intercept', models.FloatField(blank=True, null=True)),
                ('hrd_del_mh_prop', models.FloatField(blank=True, null=True)),
                ('hrd_SNV3', models.FloatField(blank=True, null=True)),
                ('hrd_SV3', models.FloatField(blank=True, null=True)),
                ('hrd_SV5', models.FloatField(blank=True, null=True)),
                ('hrd_hrdloh_index', models.FloatField(blank=True, null=True)),
                ('hrd_SNV8', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_SNV3',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_SNV8',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_SV3',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_SV5',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_del_mh_prop',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_hrdloh_index',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_intercept',
        ),
        migrations.RemoveField(
            model_name='report',
            name='hrd_probability',
        ),
    ]
