# Generated by Django 3.2 on 2021-05-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0023_labmetadata'),
        ('data_portal', '0026_auto_20210430_1053'),
    ]

    operations = [
    ]
