# Generated by Django 3.2 on 2021-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0027_merge_0023_labmetadata_0026_auto_20210430_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmetadata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
