# Generated by Django 3.2.4 on 2021-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0029_alter_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsrow',
            name='override_cycles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='limsrow',
            name='workflow',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
