# Generated by Django 3.2.7 on 2021-09-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0030_auto_20210621_0440'),
        ('data_portal', '0031_alter_report_type'),
    ]

    operations = [
    ]
