# Generated by Django 3.2.7 on 2021-09-28 04:56

import data_portal.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0032_merge_0030_auto_20210621_0440_0031_alter_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gds_file_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_uri',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='report',
            name='unique_hash',
            field=data_portal.fields.HashField(base_fields=['subject_id', 'sample_id', 'library_id', 'type', 'report_uri'], default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('msi', 'Msi'), ('tmb', 'Tmb'), ('tmb_trace', 'Tmb Trace'), ('fusion_caller_metrics', 'Fusion Caller Metrics'), ('failed_exon_coverage_qc', 'Failed Exon Coverage Qc'), ('sample_analysis_results', 'Sample Analysis Results'), ('target_region_coverage', 'Target Region Coverage'), ('qc_summary', 'Qc Summary'), ('multiqc', 'Multiqc'), ('report_inputs', 'Report Inputs'), ('hrd_chord', 'Hrd Chord'), ('hrd_hrdetect', 'Hrd Hrdetect'), ('purple_cnv_germ', 'Purple Cnv Germ'), ('purple_cnv_som', 'Purple Cnv Som'), ('purple_cnv_som_gene', 'Purple Cnv Som Gene'), ('sigs_dbs', 'Sigs Dbs'), ('sigs_indel', 'Sigs Indel'), ('sigs_snv_2015', 'Sigs Snv 2015'), ('sigs_snv_2020', 'Sigs Snv 2020'), ('sv_unmelted', 'Sv Unmelted'), ('sv_melted', 'Sv Melted'), ('sv_bnd_main', 'Sv Bnd Main'), ('sv_bnd_purpleinf', 'Sv Bnd Purpleinf'), ('sv_nobnd_main', 'Sv Nobnd Main'), ('sv_nobnd_other', 'Sv Nobnd Other'), ('sv_nobnd_manygenes', 'Sv Nobnd Manygenes'), ('sv_nobnd_manytranscripts', 'Sv Nobnd Manytranscripts')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
