# Generated by Django 3.2.7 on 2021-10-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0034_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('library_id', models.CharField(max_length=255)),
                ('instrument_run_id', models.CharField(max_length=255)),
                ('run_id', models.CharField(max_length=255)),
                ('lane', models.IntegerField()),
                ('override_cycles', models.CharField(max_length=255)),
                ('coverage_yield', models.CharField(max_length=255, null=True)),
                ('qc_pass', models.BooleanField(default=False, null=True)),
                ('qc_status', models.CharField(max_length=255, null=True)),
                ('valid_for_analysis', models.BooleanField(default=True, null=True)),
            ],
            options={
                'unique_together': {('library_id', 'instrument_run_id', 'run_id', 'lane')},
            },
        ),
    ]
