# Generated by Django 3.2.7 on 2021-10-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0035_libraryrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryrun',
            name='workflows',
            field=models.ManyToManyField(to='data_portal.Workflow'),
        ),
    ]
