# Generated by Django 3.2.7 on 2021-11-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portal', '0036_libraryrun_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrun',
            name='lane',
            field=models.IntegerField(null=True),
        ),
    ]
